### ISSUE TITLE
base_footprint missing for mobile manipulator in chapter 3

### ISSUE THREAD

**Issue by fjp** [PacktPublishing/ROS-Robotics-Projects-SecondEdition#2]
Hi, thank you for this awesome ROS book. I have a question to chapter 3: according to [REP-120](https://www.ros.org/reps/rep-0120.html#base-footprint) a robot usually has a `base_footprint` link. Why is this link tag not present in the mobile manipulator covered in chapter 3? At least I couldn't find a `base_footprint` in the urdf/xacro files in [chapter3/robot_description](https://github.com/PacktPublishing/ROS-Robotics-Projects-SecondEdition/tree/master/chapter_3_ws/src/robot_description) of this repository. Could you also please explain why it is suggested to use the `base_footprint` mentioned in REP-120?

**Comment by qboticslabs** [comment]
Hi @fjp 

What you mentioned is true. The REP-120 mentioning about base_footprint. In the case of the mobile robots, it is not mandatory though, because of most of the packages like SLAM, AMCL look for **base_link** instead of **base_footprint**. For eg. The TF tree of SLAM will be map->odom->base_link etc. So we can put base_footprint in URDF, even if you don't put it, still, it will work. I hope that will fix your doubt.

**Comment by fjp** [comment]
Thanks for the insight @qboticslabs :+1: I didn't know that most of the packages look for just **base_link**. Do you know of any scenario where **base_footprint** is required though? Otherwise I don't know why REP-120 suggests using it. Would you suggest not putting it in the URDF?

**Comment by qboticslabs** [comment]
Hi @fjp 

I used to put base_footprint according to REP-120 in my current projects as well. It will be better to follow the conventions.
